## **Operadores de comparacion**

<div style="display:flex; justify-content:space-around;">
    <img src="./imagenes/1.jpg" width=400/>
</div>

In [ ]:
import numpy as np
np_altura=np.array([1.72,1.68,1.71,1.89,1.79])

np_peso=np.array([84.4,59.2,63.6,88.4,68.7])
imc=np_peso/np_altura**2
print(imc)

[28.52893456 20.97505669 21.75028214 24.7473475  21.44127836]


In [6]:
imc>24

array([ True, False, False,  True, False])

In [8]:
imc[imc>24]

array([28.52893456, 24.7473475 ])

In [ ]:
#Para usar operadores logicos en arreglos en lugar de usar and or not
#? Existen logical_and(), logogical_or(), logical_not() 

In [10]:
np.logical_and(imc>24,imc<26)

array([False, False, False,  True, False])

In [11]:
imc[np.logical_and(imc>24,imc<26)]

array([24.7473475])

In [14]:
np.logical_or(imc<24,imc>26)

array([ True,  True,  True, False,  True])

In [15]:
imc[np.logical_or(imc<24,imc>26)]

array([28.52893456, 20.97505669, 21.75028214, 21.44127836])